name: Build

on:
  push:
  schedule:
    - cron: '0 2 * * SAT'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Linux Debug"
            os: ubuntu-20.04
            mode: Debug
          - name: "macOS Debug"
            os: macOS-11
            mode: Debug
          - name: "Windows Debug"
            os: windows-2019
            mode: Debug

    steps:
      - uses: actions/checkout@v2

      - name: Define local variables
        shell: bash
        run: |
          echo "MODE=${{matrix.mode}}"  >> $GITHUB_ENV

      - name: Explain current config
        shell: bash
        run: |
          if ( command -v make >/dev/null 2>&1 ); then
            echo "Make config: $(command -v make)"
            make --version 2>&1 | sed 's/^/  /'
          else
            echo "No make command found"
          fi

      - name: Configure
        shell: bash
        run: |
          set -x
          mkdir build && cd build
          cmake \
                -DBUILD_EXAMPLE=ON \
                -DCMAKE_BUILD_TYPE="${MODE}" \
                ..

      - name: Compile
        shell: bash
        run: |
          cd build
          cmake --build .

      - name: Test
        shell: bash
        run: |
          cd build
          ctest -C ${MODE}
          